version: "3.9"
name: app

services:
  db:
    container_name: postgresql-dev
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_USER} -h db"]
      interval: 5s
      retries: 10

  server:
    container_name: server-dev
    build:
      context: ./.devcontainer
    ports:
      - 8000:8000
      - 2345:2345 # debugging port
    volumes:
      - .:/home/dev/app
      - ./.ssh:/home/dev/.ssh
    env_file:
      - .env
    command: >
      sh -c "
        while sleep 1000; do :; done
      "